//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaltyCalculationService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_trans_details
    {
        public int id { get; set; }
        public string book_name { get; set; }
        public Nullable<System.DateTime> checkout_date { get; set; }
        public Nullable<System.DateTime> returned_date { get; set; }
        public Nullable<int> country_id { get; set; }
    }
}
