//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaltyCalculationService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PenaltyCalculationEntities : DbContext
    {
        public PenaltyCalculationEntities()
            : base("name=PenaltyCalculationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book_trans_details> book_trans_details { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<country_holiday> country_holiday { get; set; }
        public virtual DbSet<country_weekends> country_weekends { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
